version: "3"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    links:
      - server
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "5001:3001"
    links:
      - mongo      
  mongo:
    image: mongo
    container_name: database
    ports:
      - "27017:27017"
